echo "REACT_APP_AWS_ACCESS_KEY_ID=${REACT_APP_AWS_ACCESS_KEY_ID}" >> .env
echo "REACT_APP_AWS_SECRET_ACCESS_KEY=${REACT_APP_AWS_SECRET_ACCESS_KEY}" >> .env
echo "REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION}" >> .env

echo "REACT_APP_LANGUAGETOOL_API_URL=${REACT_APP_LANGUAGETOOL_API_URL}" >> .env


echo "REACT_APP_GPT_API_KEY=${REACT_APP_GPT_API_KEY}" >> .env
echo "REACT_APP_DEEPSEEK_API_KEY=${REACT_APP_DEEPSEEK_API_KEY}" >> .env
echo "REACT_APP_DEEPSEEK_API_URL=${REACT_APP_DEEPSEEK_API_URL}" >> .env

echo "Envionement Variables file Generated"
