name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Configure ESLint
        run: |
          echo '{
            "parser": "@babel/eslint-parser",
            "parserOptions": {
              "ecmaVersion": 2021,
              "sourceType": "module",
              "ecmaFeatures": { "jsx": true },
              "requireConfigFile": false,
              "babelOptions": { "presets": ["@babel/preset-react"] }
            },
            "env": {
              "browser": true,
              "es2021": true,
              "jest": true
            },
            "plugins": ["security"],
            "rules": {
              "security/detect-object-injection": ["error", {
                "exceptionPatterns": ["^GrammarCorrection\\."]
              }],
              "security/detect-non-literal-require": 2,
              "security/detect-possible-timing-attacks": 2
            },
            "overrides": [
              {
                "files": ["**/*.test.js", "**/*.spec.js"],
                "rules": {
                  "security/detect-object-injection": "off"
                }
              }
            ]
          }' > .eslintrc.json

      - name: Run ESLint
        run: npx eslint src/ --max-warnings=0
