name: Lint and Security Check

on:
  push:
    branches: [main, Errors, Development, release/v1.0.0]
  pull_request:
    branches: [main, Errors, Development, release/v1.0.0]

jobs:
  lint-and-security:
    name: ESLint & Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install --legacy-peer-deps \
            eslint@latest \
            eslint-plugin-security@latest \
            @babel/eslint-parser@latest \
            @babel/preset-react@latest
          npx update-browserslist-db@latest

      - name: Configure ESLint
        run: |
          cat << 'EOF' > .eslintrc.json
          {
            "parser": "@babel/eslint-parser",
            "parserOptions": {
              "ecmaVersion": 2021,
              "sourceType": "module",
              "ecmaFeatures": { "jsx": true },
              "requireConfigFile": false,
              "babelOptions": { "presets": ["@babel/preset-react"] }
            },
            "env": {
              "browser": true,
              "es2021": true,
              "jest": true
            },
            "extends": ["eslint:recommended"],
            "plugins": ["security"],
            "rules": {
              "security/detect-object-injection": ["error", {
                "exceptionPatterns": ["^GrammarCorrection\\."]
              }],
              "security/detect-non-literal-require": "error",
              "security/detect-possible-timing-attacks": "error"
            },
            "overrides": [
              {
                "files": ["**/*.test.js", "**/*.spec.js"],
                "rules": {
                  "security/detect-object-injection": "off"
                }
              }
            ]
          }
          EOF

      - name: Create reports directory
        run: mkdir -p ./eslint-reports

      - name: Run ESLint with security checks
        run: |
          if [ -d "src" ]; then
            npx eslint src/ \
              --rule 'security/detect-object-injection: ["error", { "exceptionPatterns": ["^GrammarCorrection\\."] }]' \
              --rule 'security/detect-non-literal-require: error' \
              --rule 'security/detect-possible-timing-attacks: error' \
              -f json -o ./eslint-reports/eslint-report.json || true
          else
            echo '[]' > ./eslint-reports/eslint-report.json
            echo "Warning: src directory not found - created empty report"
          fi

      - name: List generated files (debug)
        run: |
          echo "Generated files:"
          ls -la ./eslint-reports/
          echo "Report content:"
          cat ./eslint-reports/eslint-report.json || echo "No report file found"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: eslint-security-report
          path: ./Pages/test-reports
