name: PR Checks
on:
  pull_request:
    branches: [main]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: |
          npm test -- --coverage --watchAll=false
          if [ $(grep -oP 'Lines.*?\K\d+' coverage/lcov.info) -lt 80 ]; then
            echo "❌ Coverage < 80%"
            exit 1
          fi

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage/