name: Advanced Security Scan
on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Weekly scans

jobs:
  advanced-security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

      # Built-in secret scanning (no additional tools needed)
      - name: Secret Scanning Alert
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "GitHub automatically scans for secrets on push events"
          echo "View results at: https://github.com/${{ github.repository }}/security/secret-scanning"