name: Security Scans

on:
  push:
    branches: [main, Errors, Development, release/v1.0.0]
  pull_request:
    branches: [main, Errors, Development, release/v1.0.0]
  schedule:
    - cron: '0 0 * * 1'  # Weekly scans

env:
  REPORTS_DIR: ${{ github.workspace }}/security-reports

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p $REPORTS_DIR && chmod -R 777 $REPORTS_DIR

      - name: OWASP Dependency Scan
        uses: dependency-check/Dependency-Check_Action@v3.1.0
        with:
          project: 'Office_Tools_Kit'
          path: 'src/'
          format: 'ALL'
          out: '${{ env.REPORTS_DIR }}/dependency-check'
          args: '--scan "src/" --disableYarnAudit --disableNodeAudit --skip "**/__tests__/**" --skip "**/cypress/**" --skip "**/node_modules/**" --failOnCVSS 7'

      - name: Generate npm audit report
        run: |
          npm install
          npm audit --json > $REPORTS_DIR/npm-audit-report.json || echo '{"error": "npm audit failed"}' > $REPORTS_DIR/npm-audit-report.json

      - name: Check React DevContainer Features
        run: |
          if [ -f .devcontainer/devcontainer.json ]; then
            jq -r '.features | to_entries[] | "\(.key): \(.value.version)"' .devcontainer/devcontainer.json \
              > $REPORTS_DIR/devcontainer-features.txt || echo "No features found" > $REPORTS_DIR/devcontainer-features.txt
          else
            echo "No devcontainer.json found" > $REPORTS_DIR/devcontainer-features.txt
          fi

      - name: Upload all dependency reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-reports
          path: ${{ env.REPORTS_DIR }}/
        if: always()

  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create reports directory
        run: mkdir -p $REPORTS_DIR && chmod -R 777 $REPORTS_DIR

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          args: '--no-git --report-format json --report-path ${{ env.REPORTS_DIR }}/gitleaks-report.json'

      - name: Check Env Variables
        run: |
          grep -r 'REACT_APP_' src/ > $REPORTS_DIR/react-env-vars.txt  || echo "No React env variables found" > $REPORTS_DIR/react-env-vars.txt
          grep -r 'process.env' src/ >> $REPORTS_DIR/react-env-vars.txt || true

      - name: Upload secret scan reports
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-reports
          path: ${{ env.REPORTS_DIR }}/
        if: always()

  codespaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p $REPORTS_DIR && chmod -R 777 $REPORTS_DIR

      - name: Validate DevContainer Config
        run: |
          {
            echo "=== DevContainer Security Checks ==="
            if [ -f .devcontainer/devcontainer.json ]; then
              jq -e '.containerUser != "root"' .devcontainer/devcontainer.json && echo "containerUser OK" || echo "containerUser WARNING: Using root"
              jq -e '.remoteUser != "root"' .devcontainer/devcontainer.json && echo "remoteUser OK" || echo "remoteUser WARNING: Using root"
              jq -e '.postCreateCommand | contains("sudo") | not' .devcontainer/devcontainer.json && echo "no sudo in postCreate" || echo "WARNING: sudo found in postCreate"
              jq -e '.customizations.vscode.settings["security.workspace.trust.enabled"] == true' .devcontainer/devcontainer.json && echo "workspace.trust enabled" || echo "WARNING: workspace.trust not enabled"
            else
              echo "No devcontainer.json found"
            fi
          } > $REPORTS_DIR/codespaces-check.log

      - name: Verify React Ports
        run: |
          {
            echo "=== Forwarded Ports ==="
            if [ -f .devcontainer/devcontainer.json ]; then
              jq '.forwardPorts' .devcontainer/devcontainer.json || echo "No forwarded ports configured"
            else
              echo "No devcontainer.json found"
            fi
          } >> $REPORTS_DIR/codespaces-check.log

      - name: Upload Codespaces reports
        uses: actions/upload-artifact@v4
        with:
          name: codespaces-reports
          path: ${{ env.REPORTS_DIR }}/
        if: always()
