name: Third party Security Scans 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly scans

jobs:
  # 1. SAST (Static Application Security Testing)
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Semgrep (Pattern-based scanning)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

      # CodeQL (Limited version without GHAS)
      - name: CodeQL Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v2

  # 2. Dependency Scanning
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # NPM Audit
      - name: NPM Audit
        run: |
          npm install
          npm audit --audit-level=high

      # OWASP Dependency Check
      - name: OWASP Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'My_Private_Repo'
          format: 'HTML'
          failOnCVSS: 7

  # 3. Secret Scanning
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # TruffleHog (High-entropy secret detection)
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          args: '--regex --entropy=False github.com/your/repo'

      # Gitleaks (Pattern-based secret detection)
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
