name: Test

on:
  push:
    branches: [main, Errors, Development, release/v1.0.0,ColdFix]
  pull_request:
    branches: [main, Errors, Development, release/v1.0.0, ColdFix]

jobs:
  unit-tests:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests & generate reports
        run: |
          npm test \
            -- --watchAll=false \
               --coverage \
               --passWithNoTests \
               --reporters=default \
               --reporters=jest-junit \
               --outputFile=junit.xml
        env:
          CI: true

      - name: Verify test artifacts exist
        run: |
          mkdir -p test-artifacts
          [ -f junit.xml ] && cp junit.xml test-artifacts/ || echo "No JUnit report found" > test-artifacts/junit-missing.txt
          [ -d coverage ] && cp -r coverage/ test-artifacts/ || echo "No coverage report found" > test-artifacts/coverage-missing.txt

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: test-artifacts/
          retention-days: 7

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: junit.xml
          retention-days: 7
