name: Test

on:
  push:
    branches: [main, Errors, Development, release/v1.0.0]
  pull_request:
    branches: [main, Errors, Development, release/v1.0.0]

jobs:
  unit-tests:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev jest-junit

      - name: Run unit tests with coverage
        env:
          CI: true
          JEST_JUNIT_OUTPUT_DIR: test-results
          JEST_JUNIT_OUTPUT_NAME: junit.xml
        run: |
          mkdir -p test-results
          npm test -- --watchAll=false \
                     --coverage \
                     --passWithNoTests \
                     --reporters=default \
                     --reporters=jest-junit

      - name: Verify test artifacts
        run: |
          mkdir -p coverage
          if [ ! -f "test-results/junit.xml" ]; then
            echo '<testsuites/>' > test-results/junit.xml
          fi
          if [ ! -d "coverage" ]; then
            mkdir -p coverage
            echo '{}' > coverage/coverage-final.json
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/junit.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/

      - name: Print test summary
        run: |
          echo "=== Test Summary ==="
          if [ -f "test-results/junit.xml" ]; then
            echo "JUnit report exists"
          else
            echo "No JUnit report generated"
          fi
          if [ -d "coverage" ]; then
            echo "Coverage report exists"
          else
            echo "No coverage report generated"
          fi
